name: Deploy to Google Cloud Run

on:
  push:
    branches: [ 'development' ]
  release:
    types: [ 'published' ]

jobs:
  setup:
    name: Setup Deployment
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.set-env.outputs.env }}
      gcp_project: ${{ steps.set-env.outputs.gcp_project }}
      workload_identity_provider: ${{ steps.set-env.outputs.workload_identity_provider }}
      service_account: ${{ steps.set-env.outputs.service_account }}
      region: ${{ steps.set-env.outputs.region }}
      backend_url: ${{ steps.set-env.outputs.backend_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Environment
        id: set-env
        run: |
          # Determine environment based on GitHub event
          if ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}; then
            ENV="dev"
            PROJECT="${{ vars.GCP_PROJECT_NONPROD }}"
            WI_PROVIDER="${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_NONPROD }}"
            SA="${{ vars.GCP_SERVICE_ACCOUNT_NONPROD }}"
            BACKEND_URL="${{ vars.BACKEND_URL_NONPROD }}"
            echo "Deploying to DEV environment"
          elif ${{ github.event_name == 'release' }}; then
            ENV="prod"
            PROJECT="${{ vars.GCP_PROJECT_PROD }}"
            WI_PROVIDER="${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_PROD }}"
            SA="${{ vars.GCP_SERVICE_ACCOUNT_PROD }}"
            BACKEND_URL="${{ vars.BACKEND_URL_PROD }}"
            echo "Deploying to PROD environment"
          else
            echo "No environment determined"
            exit 1
          fi

          echo "env=$ENV" >> $GITHUB_OUTPUT
          echo "gcp_project=$PROJECT" >> $GITHUB_OUTPUT
          echo "workload_identity_provider=$WI_PROVIDER" >> $GITHUB_OUTPUT
          echo "service_account=$SA" >> $GITHUB_OUTPUT
          echo "region=${{ vars.GCP_REGION }}" >> $GITHUB_OUTPUT
          echo "backend_url=$BACKEND_URL" >> $GITHUB_OUTPUT

  build-docsite-live:
    name: Build DocSite Live
    needs: [setup]
    uses: ./.github/workflows/reusable-node.yml
    with:
      image_name: docsite-live
      tag: ${{ needs.setup.outputs.env }}
      gcp_project: ${{ needs.setup.outputs.gcp_project }}
      gcp_region: ${{ needs.setup.outputs.region }}
      workload_identity_provider: ${{ needs.setup.outputs.workload_identity_provider }}
      service_account: ${{ needs.setup.outputs.service_account }}
      vite_mode: production
      vite_backend_url: ${{ needs.setup.outputs.backend_url }}/api/v1/production/docs

  build-visual-editor:
    name: Build Visual Editor
    needs: [setup]
    uses: ./.github/workflows/reusable-node.yml
    with:
      image_name: visual-editor
      tag: ${{ needs.setup.outputs.env }}
      gcp_project: ${{ needs.setup.outputs.gcp_project }}
      gcp_region: ${{ needs.setup.outputs.region }}
      workload_identity_provider: ${{ needs.setup.outputs.workload_identity_provider }}
      service_account: ${{ needs.setup.outputs.service_account }}
      vite_mode: visual-editor
      vite_backend_url: ${{ needs.setup.outputs.backend_url }}/api/v1/visual-editor/docs

  deploy-docsite-live:
    name: Deploy Docsite Live to Cloud Run
    needs: [setup, build-docsite-live]
    uses: ./.github/workflows/reusable-deploy-cloudrun.yml
    with:
      service_name: docsite-live
      env: ${{ needs.setup.outputs.env }}
      gcp_project: ${{ needs.setup.outputs.gcp_project }}
      region: ${{ needs.setup.outputs.region }}
      workload_identity_provider: ${{ needs.setup.outputs.workload_identity_provider }}
      service_account: ${{ needs.setup.outputs.service_account }}

  deploy-visual-editor:
    name: Deploy Visual Editor to Cloud Run
    needs: [setup, build-visual-editor]
    uses: ./.github/workflows/reusable-deploy-cloudrun.yml
    with:
      service_name: visual-editor
      env: ${{ needs.setup.outputs.env }}
      gcp_project: ${{ needs.setup.outputs.gcp_project }}
      region: ${{ needs.setup.outputs.region }}
      workload_identity_provider: ${{ needs.setup.outputs.workload_identity_provider }}
      service_account: ${{ needs.setup.outputs.service_account }}
